# Generated by Django 5.2.17 on 2026-09-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_subjects',
            field=models.ManyToManyField(blank=True, help_text='Selecțiile din onboarding. Semnal de pornire pentru recomandări.', related_name='interested_profiles', to='catalog.subject'),
        ),
    ]
