# Generated by Django 5.2.17 on 2026-09-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinglist',
            options={'ordering': ['-updated_at'], 'verbose_name': 'listă de lectură', 'verbose_name_plural': 'liste de lectură'},
        ),
        migrations.AlterModelOptions(
            name='readinglistitem',
            options={'ordering': ['position'], 'verbose_name': 'titlu din listă', 'verbose_name_plural': 'titluri din listă'},
        ),
    ]
