# Generated by Django 5.2.17 on 2026-09-03 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOK_SAVED', 'Salvată'), ('READING_STARTED', 'Începută'), ('READING_FINISHED', 'Terminată'), ('BOOK_LIKED', 'Apreciată'), ('BOOK_DISLIKED', 'Respinsă'), ('BOOK_REMOVED', 'Scoasă din raft')], max_length=24)),
                ('value', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='reader_inte_user_id_2f4a86_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('page', 'Pagină'), ('percentage', 'Procent'), ('chapter', 'Capitol'), ('epubcfi', 'EPUB CFI')], default='page', max_length=16)),
                ('location_value', models.CharField(default='1', max_length=120)),
                ('percentage', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='catalog.bookresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'resource'), name='uniq_user_resource_progress'), models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='progress_percentage_range')],
            },
        ),
        migrations.CreateModel(
            name='UserBookState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WANT_TO_READ', 'Vreau să citesc'), ('READING', 'Citesc acum'), ('FINISHED', 'Terminată'), ('ABANDONED', 'Abandonată')], default='WANT_TO_READ', max_length=16)),
                ('reaction', models.CharField(blank=True, choices=[('LIKE', 'Mi-a plăcut'), ('NEUTRAL', 'Neutru'), ('DISLIKE', 'Nu mi-a plăcut')], max_length=8)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='uniq_user_book_state')],
            },
        ),
    ]
