# Generated by Django 5.2.17 on 2026-09-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='last_session_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='session_count',
            field=models.PositiveIntegerField(default=0, help_text='Câte salvări distincte de poziție au avut loc.'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='total_reading_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minute de lectură estimate din intervalele dintre salvări.'),
        ),
    ]
