# Generated by Django 5.2.17 on 2026-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_readingprogress_last_session_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingprogress',
            name='session_count',
            field=models.PositiveIntegerField(default=0, help_text='Câte sesiuni distincte de lectură au avut loc.'),
        ),
    ]
