# Generated by Django 5.2.17 on 2026-09-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_readingprogress_session_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactionevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'eveniment de interacțiune', 'verbose_name_plural': 'evenimente de interacțiune'},
        ),
        migrations.AlterModelOptions(
            name='userbookstate',
            options={'ordering': ['-updated_at'], 'verbose_name': 'stare de lectură', 'verbose_name_plural': 'stări de lectură'},
        ),
    ]
