# Generated by Django 5.2.17 on 2026-09-03 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('kind', models.CharField(choices=[('GENRE', 'Gen'), ('TOPIC', 'Temă'), ('EDUCATIONAL', 'Arie educațională')], default='GENRE', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('description', models.TextField(blank=True)),
                ('original_language', models.CharField(default='ro', max_length=8)),
                ('first_publish_year', models.PositiveIntegerField(blank=True, null=True)),
                ('recommended_age', models.CharField(blank=True, choices=[('7-9', '7-9 ani'), ('10-12', '10-12 ani'), ('13-15', '13-15 ani'), ('16-18', '16-18 ani'), ('ADULT', 'Adult')], max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RIGHTS_REVIEW', 'Verificare drepturi'), ('READY', 'Pregătită'), ('PUBLISHED', 'Publicată'), ('ARCHIVED', 'Arhivată')], default='DRAFT', max_length=16)),
                ('featured', models.BooleanField(default=False, help_text='Selecția bibliotecarului')),
                ('source_name', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='catalog.author')),
                ('subjects', models.ManyToManyField(blank=True, related_name='books', to='catalog.subject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(default='ro', max_length=8)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn_10', models.CharField(blank=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, max_length=13)),
                ('cover_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='catalog.book')),
            ],
            options={
                'ordering': ['-is_primary', 'publication_year'],
            },
        ),
        migrations.CreateModel(
            name='BookResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB'), ('HTML', 'HTML'), ('TXT', 'Text'), ('EXTERNAL', 'Link extern')], max_length=16)),
                ('storage_type', models.CharField(choices=[('LOCAL', 'Fișier local'), ('EXTERNAL', 'URL extern')], default='LOCAL', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='books/')),
                ('external_url', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('rights_status', models.CharField(choices=[('UNKNOWN', 'Neverificat'), ('VERIFIED', 'Verificat'), ('REJECTED', 'Respins')], default='UNKNOWN', max_length=16)),
                ('license_name', models.CharField(blank=True, max_length=120)),
                ('license_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('rights_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalog.bookedition')),
                ('rights_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('external_url', ''), ('storage_type', 'LOCAL')), ('storage_type', 'EXTERNAL'), _connector='OR'), name='resource_storage_coherent')],
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source_name', 'external_id'), name='uniq_book_external_source'),
        ),
    ]
