# Generated by Django 5.2.17 on 2026-09-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookresource',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Numărul total de pagini. Permite calculul automat al procentului.', null=True),
        ),
    ]
