# Generated by Django 5.2.17 on 2026-09-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookresource_total_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'autor', 'verbose_name_plural': 'autori'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'carte', 'verbose_name_plural': 'cărți'},
        ),
        migrations.AlterModelOptions(
            name='bookedition',
            options={'ordering': ['-is_primary', 'publication_year'], 'verbose_name': 'ediție', 'verbose_name_plural': 'ediții'},
        ),
        migrations.AlterModelOptions(
            name='bookresource',
            options={'ordering': ['-is_primary', 'id'], 'verbose_name': 'resursă', 'verbose_name_plural': 'resurse'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'temă', 'verbose_name_plural': 'teme'},
        ),
    ]
